name: somafm-qt
base: core18
version: 'master'
summary: SomaFM Radio (somafm.com) player (desktop, qt5)
description: |
  SomaFM Radio (somafm.com) player (desktop, qt5)
grade: devel
confinement: strict

apps:
  somafm-qt:
    command: desktop-launch $SNAP/usr/bin/somafm-qt
    environment:
      LD_LIBRARY_PATH: $LD_LIBRARY_PATH:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pulseaudio
    plugs: 
      - home
      - unity7
      - desktop
      - desktop-legacy
      - network
      - opengl
      - pulseaudio
      - wayland
      - x11

parts:
  somafm-qt:
    source: https://github.com/fredix/somafm-qt.git
    source-type: git
    plugin: qmake
    build-packages:
      - qtbase5-dev
      - qtmultimedia5-dev
      - wayland-protocols
    stage-packages: 
      - libqt5gui5
      - libqt5multimedia5
      - libqt5multimedia5-plugins
      - libqt5widgets5
#      - libqt5dbus5
#      - libqt5core5a
#      - qt5-default
      - gstreamer1.0-pulseaudio
      - gstreamer1.0-plugins-good
      - gstreamer1.0-plugins-ugly
      - gstreamer1.0-plugins-bad
      - libslang2
      - libgpm2
    after: [desktop-qt5]

  desktop-qt5:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-branch: stable
    source-subdir: qt
    plugin: make
